### ISSUE TITLE
FileExistsError: [Errno 17] File exists: '/tmp/tmpvett9j9p'

### ISSUE THREAD

**Issue by jonnydefijn** [eli64s/readme-ai#10]
OS: `Fedora Linux 38`

Command:

```
python src/main.py --api-key 12345 --output docs/README.md --local /home/pc/dev/project
```

Error:

```
2023-05-11 11:23:13 | INFO | logger:info:32 - README-AI is now executing.
2023-05-11 11:23:13 | INFO | logger:info:32 - Using local directory: /home/pc/dev/project
Traceback (most recent call last):

  File "/home/pc/README-AI/src/main.py", line 133, in <module>
    app()

  File "/home/pc/README-AI/src/main.py", line 32, in main
    asyncio.run(generate_readme(api_key, local, output, remote))

  File "/home/pc/.conda/envs/readmeai/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)

  File "/home/pc/.conda/envs/readmeai/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()

  File "/home/pc/README-AI/src/main.py", line 51, in generate_readme
    dependencies = preprocess.get_project_dependencies(repo, file_exts, file_names)

  File "/home/pc/README-AI/src/preprocess.py", line 201, in get_project_dependencies
    _clone_or_copy_repository(repo, temp_dir)

  File "/home/pc/README-AI/src/preprocess.py", line 46, in _clone_or_copy_repository
    shutil.copytree(repo, temp_dir)

  File "/home/pc/.conda/envs/readmeai/lib/python3.10/shutil.py", line 559, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,

  File "/home/pc/.conda/envs/readmeai/lib/python3.10/shutil.py", line 457, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)

  File "/home/pc/.conda/envs/readmeai/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)

FileExistsError: [Errno 17] File exists: '/tmp/tmpvett9j9p'
```

**Comment by eli64s** [comment]
@jonnydefijn Was this error message on your first try, or did you previously run the command successfully using the local directory?

**Comment by jonnydefijn** [comment]
> @jonnydefijn Was this error message on your first try, or did you previously run the command successfully using the local directory?

First try.

**Comment by Andythem23** [comment]
Same

**Comment by eli64s** [comment]
@jonnydefijn @Andythem23 Thanks for the info and testing out the tool! 

I've reproduced the error with a local directory and will work on correcting this issue.

If you have the repository on GitHub, please try the remote option for now as that should work.

Thanks!

**Comment by eli64s** [comment]
@jonnydefijn @Andythem23 I have updated the code to fix the **_FileExistsError_**. 

Can you clone the updates and let me know if that solves the issue for you? Thanks!

**Comment by jonnyhoff** [comment]
Not getting the `File Exists` error anymore.

Now getting :

```
RateLimitError: The server had an error while processing your request. Sorry about that!
```

**Comment by eli64s** [comment]
@jonnydefijn just pushed some updates for API errors. It should properly handle everything now.

Let me know if you have anymore issues!
