### ISSUE TITLE
'ResourceExhausted' object is not iterable

### ISSUE THREAD

**Issue by hongha1412** [eli64s/readme-ai#114]
Hi guys,

I'm trying to use readme-ai to generate readme for my local repository with command:
```
docker run -it -e GOOGLE_API_KEY=$GOOGLE_API_KEY -v "$(pwd)":/app zeroxeli/readme-ai:latest -r ./my-large-project --api GEMINI -m gemini-1.0-pro --tree-depth 4 -t 0.9 -o readme.md --context-window 9999 --rate-limit 100
```
the above command encounterred error ResourceExhausted

```
Traceback (most recent call last):
  File "/home/tempuser/.local/lib/python3.10/site-packages/readmeai/_agent.py", line 77, in readme_agent
    asyncio.run(readme_generator(conf, output_file))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/tempuser/.local/lib/python3.10/site-packages/readmeai/_agent.py", line 122, in readme_generator
    ).build()
  File "/home/tempuser/.local/lib/python3.10/site-packages/readmeai/generators/builder.py", line 121, in build
    self.md_summaries,
  File "/home/tempuser/.local/lib/python3.10/site-packages/readmeai/generators/builder.py", line 65, in md_summaries
    summaries = tables.format_code_summaries(
  File "/home/tempuser/.local/lib/python3.10/site-packages/readmeai/generators/tables.py", line 58, in format_code_summaries
    for summary in code_summaries:
TypeError: 'ResourceExhausted' object is not iterable
```
How could i resolve this?

**Comment by trystan2k** [comment]
Hi,

I am also getting this problem, any idea on how to solve it ?

Thanks !

**Comment by warmfire540** [comment]
rate limit seems to be a semaphore in the code.. not checking RPM actually, just eyeballing
