### ISSUE TITLE
Error When Generating the README File Through OpenAI

### ISSUE THREAD

**Issue by mmaisonette** [eli64s/readme-ai#120]
I'm trying to run the following command to generate a README file from a project I'm working on.

```shell
docker run -it --rm \
-e OPENAI_API_KEY=$OPENAI_API_KEY \
-v "$(pwd)":/app zeroxeli/readme-ai:latest \
-r https://github.com/mmaisonette/currency-converter \
--api openai
``` 

The result of this command is this:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 114, in __call__
    result = await fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/readmeai/models/openai.py", line 99, in _make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1135, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url='https://api.openai.com/v1/chat/completions'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/readmeai/__main__.py", line 32, in error_handler
    yield
  File "/usr/local/lib/python3.11/site-packages/readmeai/__main__.py", line 40, in readme_agent
    asyncio.run(readme_generator(config, output_file))
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/readmeai/__main__.py", line 56, in readme_generator
    responses = await llm.batch_request()
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/readmeai/models/base.py", line 102, in batch_request
    summaries_responses = await self._batch_prompts(summaries_prompts)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/readmeai/models/base.py", line 122, in _batch_prompts
    batch_responses = await asyncio.gather(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/readmeai/models/base.py", line 142, in _process_batch
    return await self._make_request_code_summary(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/readmeai/models/base.py", line 177, in _make_request_code_summary
    _, summary_or_error = await self._make_request(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 189, in async_wrapped
    return await copy(fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 111, in __call__
    do = await self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 419, in exc_check
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7ffffbf82210 state=finished raised ClientResponseError>]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/readmeai", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/readmeai/cli/main.py", line 90, in main
    readme_agent(config=config, output_file=output)
  File "/usr/local/lib/python3.11/site-packages/readmeai/__main__.py", line 39, in readme_agent
    with error_handler():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/readmeai/__main__.py", line 34, in error_handler
    raise ReadmeGeneratorError(e) from e
readmeai.errors.ReadmeGeneratorError: Error generating README: RetryError[<Future at 0x7ffffbf82210 state=finished raised ClientResponseError>]
``` 

Do you have any suggestions about what might be going on here?

> Note: I didn't exceed the rate limit for requests to the OpenAI. That is the first time using the current token.

**Comment by mmaisonette** [comment]
That was an issue with the OpenAI token. Problem fixed!

**Comment by tomer92808888** [comment]
What have you done?

> That was an issue with the OpenAI token. Problem fixed!

**Comment by Syt0709** [comment]
> That was an issue with the OpenAI token. Problem fixed!

hi,i'm facing same problem right now, could you please tell me more about how you solved it?thank you!
