### ISSUE TITLE
Logger error during generation

### ISSUE THREAD

**Issue by MrZoidberg** [eli64s/readme-ai#122]
Got this issue:

Traceback (most recent call last):
  File "/root/.local/bin/readmeai", line 5, in <module>
    from readmeai.cli.main import main
  File "/root/.local/share/pipx/venvs/readmeai/lib/python3.9/site-packages/readmeai/cli/main.py", line 5, in <module>
    from readmeai.__main__ import readme_agent
  File "/root/.local/share/pipx/venvs/readmeai/lib/python3.9/site-packages/readmeai/__main__.py", line 13, in <module>
    from readmeai.config.settings import ConfigLoader
  File "/root/.local/share/pipx/venvs/readmeai/lib/python3.9/site-packages/readmeai/config/settings.py", line 29, in <module>
    from readmeai.generators.banner import (
  File "/root/.local/share/pipx/venvs/readmeai/lib/python3.9/site-packages/readmeai/generators/banner.py", line 5, in <module>
    from readmeai.logger import get_logger
  File "/root/.local/share/pipx/venvs/readmeai/lib/python3.9/site-packages/readmeai/logger.py", line 110, in <module>
    def get_logger(name: str | None = None) -> structlog.stdlib.BoundLogger:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

got latest version of readmeai

**Comment by surya-mu** [comment]
I got the same error, it seems type hinting using '|' is not supported, so we'll have to upgrade our exisiting python to 3.10 or above  for it to work, I upgraded my python and pip and it works now.
