### ISSUE TITLE
ValueError: 3 columns passed, passed data had 2 columns

### ISSUE THREAD

**Issue by kyryloovsiuk** [eli64s/readme-ai#22]
`python src/main.py --o readme-ai.md -r https://github.com/tuipoland/tui-infastructure-terraform-module-documentdb`

```
INFO     README-AI is now executing.
Traceback (most recent call last):
  File "/home/ll1rro/.local/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 934, in _finalize_columns_and_data
    columns = _validate_or_indexify_columns(contents, columns)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/.local/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 981, in _validate_or_indexify_columns
    raise AssertionError(
AssertionError: 3 columns passed, passed data had 2 columns

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ll1rro/Downloads/readme-ai/src/main.py", line 137, in <module>
    asyncio.run(main(args.api_key, args.output, args.repository))
  File "/usr/lib64/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ll1rro/Downloads/readme-ai/src/main.py", line 48, in main
    await generate_readme(gpt)
  File "/home/ll1rro/Downloads/readme-ai/src/main.py", line 55, in generate_readme
    dependencies, file_text = get_dependencies(scanner, repository)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/Downloads/readme-ai/src/main.py", line 75, in get_dependencies
    dependencies, file_text = scanner.get_dependencies(repository)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/Downloads/readme-ai/src/preprocess.py", line 33, in get_dependencies
    contents = self.parser.analyze(repository, is_remote)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/Downloads/readme-ai/src/preprocess.py", line 85, in analyze
    df = self.process_language_mapping(df)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/Downloads/readme-ai/src/preprocess.py", line 113, in process_language_mapping
    df[["install", "run", "test"]] = pd.DataFrame.from_records(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/.local/lib/python3.11/site-packages/pandas/core/frame.py", line 2266, in from_records
    arrays, arr_columns = to_arrays(data, columns)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/.local/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 840, in to_arrays
    content, columns = _finalize_columns_and_data(arr, columns, dtype)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ll1rro/.local/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 937, in _finalize_columns_and_data
    raise ValueError(err) from err
ValueError: 3 columns passed, passed data had 2 columns

```

**Comment by eli64s** [comment]
Hey! This is because I didn't have Terraform listed in the project's configuration files.

Adding the following lines to each file will correct this issue:

[conf/language_setup.toml](https://github.com/eli64s/README-AI/blob/main/conf/language_setup.toml): Terraform = ["terraform init", "terraform apply", "Write test instructions here"]
[conf/language_name.toml](https://github.com/eli64s/README-AI/blob/main/conf/language_names.toml): tf = "Terraform"
