### ISSUE TITLE
ValueError: Shape of passed values is (27, 1), indices imply (27, 2)

### ISSUE THREAD

**Issue by chmenegatti** [eli64s/readme-ai#24]
I'm having this trouble

| **📈 Scalability** | The codebase is designed to be scalable and modular, with various components separated into their own packages to allow for easy management and organization. The heavy use of external dependencies could potentially lead to issues with scalability, and further testing would be needed to determine the system's ability to handle larger workloads. |
Traceback (most recent call last):
  File "/home/cesar/python/README-AI/src/main.py", line 144, in <module>
    asyncio.run(main(args.api_key, args.output, args.repository))
  File "/home/cesar/anaconda3/envs/readme_ai/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/cesar/anaconda3/envs/readme_ai/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cesar/anaconda3/envs/readme_ai/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/cesar/python/README-AI/src/main.py", line 54, in main
    await generate_readme(gpt)
  File "/home/cesar/python/README-AI/src/main.py", line 74, in generate_readme
    builder.build_markdown(CONF, CONF_HELPER, dependencies, code_summary)
  File "/home/cesar/python/README-AI/src/builder.py", line 24, in build_markdown
    readme_parts = create_readme_parts(conf, conf_helper, packages, summaries)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cesar/python/README-AI/src/builder.py", line 47, in create_readme_parts
    summary_df = create_markdown_tables(summaries)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cesar/python/README-AI/src/builder.py", line 106, in create_markdown_tables
    summary_df = pd.DataFrame(summaries, columns=["Module", "Summary"])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cesar/anaconda3/envs/readme_ai/lib/python3.11/site-packages/pandas/core/frame.py", line 798, in __init__
    mgr = ndarray_to_mgr(
          ^^^^^^^^^^^^^^^
  File "/home/cesar/anaconda3/envs/readme_ai/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 337, in ndarray_to_mgr
    _check_values_indices_shape_match(values, index, columns)
  File "/home/cesar/anaconda3/envs/readme_ai/lib/python3.11/site-packages/pandas/core/internals/construction.py", line 408, in _check_values_indices_shape_match
    raise ValueError(f"Shape of passed values is {passed}, indices imply {implied}")
ValueError: Shape of passed values is (27, 1), indices imply (27, 2)

what could be?

**Comment by eli64s** [comment]
Do you have a link to the example repository?

**Comment by chmenegatti** [comment]
Yes... is this repo: https://gitlab.com/ascenty/core
