### ISSUE TITLE
can not generate readme => KeyError: 'build.gradle.kts'

### ISSUE THREAD

**Issue by flapili** [eli64s/readme-ai#45]
Hi, I have a repository with nuxt3 and tauri (alpha2) and it fail to generate readme 

```
INFO     README-AI is now executing.
INFO     Successfully validated OpenAI API key.
INFO     Model: {'endpoint': 'https://api.openai.com/v1/chat/completions', 'engine': 'gpt-3.5-turbo', 'encoding': 'cl100k_base', 'rate_limit': 5, 'tokens': 669, 'tokens_max': 3899, 'temperature': 1.2, 'api_key': '****************'}
INFO     Repository: GitConfig(repository='../la-caisse', name='la-caisse')
INFO     Successfully cloned ../la-caisse to /var/folders/yk/1zcj86td3xn84_ty8414k95c0000gn/T/tmp8z2bf1rk.
Traceback (most recent call last):
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/./venv/bin/readmeai", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/readmeai/main.py", line 131, in cli
    asyncio.run(main(api_key, output, repository))
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/readmeai/main.py", line 28, in main
    await generate_readme(llm)
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/readmeai/main.py", line 35, in generate_readme
    dependencies, file_text = get_dependencies(scanner, repository)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/readmeai/main.py", line 89, in get_dependencies
    dependencies, file_text = scanner.get_dependencies(repository)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/readmeai/preprocess.py", line 32, in get_dependencies
    dependencies = self.parser.get_dependency_file_contents(contents)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/benoitdeveaux/Documents/ugo/readme.ai/venv/lib/python3.11/site-packages/readmeai/preprocess.py", line 86, in get_dependency_file_contents
    parser = file_parsers[content["name"]]
             ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'build.gradle.kts'
```

I tried to add src-tauri to ignore file but without success

EDIT: look like there is an issue with conf file, I tried to edit the conf folder in site-packages/readmeai but it did not work (commented out
```
    # 'build.gradle',
    # 'build.gradle.kts',
    # 'pom.xml',
```

**Comment by eli64s** [comment]
@flapili Going through some older issues right now and saw this hasn't been addressed or closed! This bug should be resolved in newer versions of the `readme-ai` tool. 

You can upgrade the package using the following command.

```sh
pip install readmeai --upgrade
```

Let me know if you have any more questions or face any further errors.

Happy New Year!
*Eli*
