### ISSUE TITLE
 parser = file_parsers[content["name"]] KeyError: '<filename.ext>'

### ISSUE THREAD

**Issue by giuliozelante** [eli64s/readme-ai#47]
I correctly generated a readme with one of my personal project, but just for the sake, I tried also to do the same on one of my work projects and I get this stacktrace:

```
docker run -it -e OPENAI_API_KEY=<API_KEY> -v $(pwd):/app zeroxeli/readme-ai:latest readmeai -o README.md -r /app
INFO     README-AI is now executing.
INFO     Successfully validated OpenAI API key.
INFO     Model: {'endpoint': 'https://api.openai.com/v1/chat/completions', 'engine': 'gpt-3.5-turbo', 'encoding': 'cl100k_base', 'rate_limit': 5, 'tokens': 669, 'tokens_max': 3899, 'temperature': 1.2, 'api_key': '****************'}
INFO     Repository: GitConfig(repository='/app', name='app')
INFO     Successfully cloned /app to /tmp/tmp2yyavsyd.
INFO     Dependency file found: package.json
INFO     Dependency file found: build.gradle
INFO     Dependency file found: documentiReportRiepilogo.model.ts
Traceback (most recent call last):
  File "/home/tempuser/.local/bin/readmeai", line 8, in <module>
    sys.exit(cli())
  File "/home/tempuser/.local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/tempuser/.local/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/tempuser/.local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tempuser/.local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/tempuser/.local/lib/python3.9/site-packages/readmeai/main.py", line 131, in cli
    asyncio.run(main(api_key, output, repository))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/tempuser/.local/lib/python3.9/site-packages/readmeai/main.py", line 28, in main
    await generate_readme(llm)
  File "/home/tempuser/.local/lib/python3.9/site-packages/readmeai/main.py", line 35, in generate_readme
    dependencies, file_text = get_dependencies(scanner, repository)
  File "/home/tempuser/.local/lib/python3.9/site-packages/readmeai/main.py", line 89, in get_dependencies
    dependencies, file_text = scanner.get_dependencies(repository)
  File "/home/tempuser/.local/lib/python3.9/site-packages/readmeai/preprocess.py", line 34, in get_dependencies
    dependencies = self.parser.get_dependency_file_contents(contents)
  File "/home/tempuser/.local/lib/python3.9/site-packages/readmeai/preprocess.py", line 90, in get_dependency_file_contents
    parser = file_parsers[content["name"]]
KeyError: 'documentiReportRiepilogo.model.ts'
```

just for the sake of it here is the file:

```
import type { DocType } from './doc-type.model';

export interface ReportRiepilogoModelTable {
  id: number;
  nomeDocumento: string;
  dataPubblicazione?: string;
  destinatari: number;
  accettato: number;
  rifiutato: number;
  nonRisp: number;
  download: number;
}

export interface ReportRiepilogoModel {
  id: number;
  fileName: string;
  docTypeId: number;
  docType: DocType;
  linkedDocuments: unknown[];
  statoDocumento: string;
  read: boolean;
  proposalCount: number;
  publishDate: string;
  creationDate: string;
  countAccettato: number;
  countDownload: number;
  countNonRisposto: number;
  countRifiutato: number;
}
```

**Comment by eli64s** [comment]
Hi @giuliozelante!

Get the latest version using the command below and let me know if you still get this error.

```sh
pip install --upgrade readmeai
```

Thanks for reporting it!

**Comment by giuliozelante** [comment]
I get the same error
