### ISSUE TITLE
Stacktrace: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Acetyld** [eli64s/readme-ai#65]
Hi as title states:

` readmeai  -o=README.md --repository=https://github.com/Acetyld/expo-foreground-actions`

`ERROR    Exception: list index out of range
Stacktrace: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/readmeai/main.py", line 81, in readme_agent
    dependencies, file_text = parser.get_dependencies(temp_dir)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/readmeai/core/preprocess.py", line 107, in get_dependencies
    dependencies = self.get_dependency_file_contents(contents)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/readmeai/core/preprocess.py", line 64, in get_dependency_file_contents
    parsed_content = parser(content=content["content"])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/readmeai/core/parser.py", line 254, in parse_gradle
    return [
           ^
  File "/opt/homebrew/lib/python3.11/site-packages/readmeai/core/parser.py", line 255, in <listcomp>
    match.split(":")[-2].split(".")[-1]
    ~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range`

**Comment by eli64s** [comment]
Hi @Acetyld,

I've pushed an update to correct this error. Please install the latest version:

```sh
pip install readmeai --upgrade
```

Let me know if you're still facing issues. Thank you.

_Eli_

**Comment by Acetyld** [comment]
> Hi @Acetyld,
> 
> I've pushed an update to correct this error. Please install the latest version:
> 
> ```shell
> pip install readmeai --upgrade
> ```
> 
> Let me know if you're still facing issues. Thank you.
> 
> _Eli_

Seems to be fixed =)!

But.. same prompt now gives:

[(PosixPath('yarn.lock'), 'Prompt exceeds max token limit: 12885.'), (PosixPath('.eslintrc.js'), 'HTTPStatus Exception: 401'), (PosixPath('plugins/expo-foreground-actions.js'), 'HTTPStatus Exception: 401'), (PosixPath('example/App.tsx'), 'HTTPStatus Exception: 401'), (PosixPath('example/webpack.config.js'), 'HTTPStatus Exception: 401')]

ERROR    HTTPStatus Exception:
Client error '401 Unauthorized' for url 'https://api.openai.com/v1/chat/completions'
For more information check: https://httpstatuses.com/401
ERROR    HTTPStatus Exception:

**Comment by nachimehta** [comment]
@eli64s I am getting the original error:

```ERROR    Exception: list index out of range
Stacktrace: Traceback (most recent call last):
  File "/home/nachi/projects/venv/lib/python3.10/site-packages/readmeai/main.py", line 115, in readme_agent
    headers.build_readme_md(conf, conf_helper, dependencies, code_summary)
  File "/home/nachi/projects/venv/lib/python3.10/site-packages/readmeai/markdown/headers.py", line 24, in build_readme_md
    all_readme_sections = format_readme_md_contents(
  File "/home/nachi/projects/venv/lib/python3.10/site-packages/readmeai/markdown/headers.py", line 51, in format_readme_md_contents
    conf.md.tables = tables.create_tables(
  File "/home/nachi/projects/venv/lib/python3.10/site-packages/readmeai/markdown/tables.py", line 48, in create_tables
    table = create_table(table_data, repository, user_repo_name)
  File "/home/nachi/projects/venv/lib/python3.10/site-packages/readmeai/markdown/tables.py", line 66, in create_table
    github_url = vcs.get_github_file_link(
  File "/home/nachi/projects/venv/lib/python3.10/site-packages/readmeai/services/version_control.py", line 127, in get_github_file_link
    domain = repo.split("/")[2]
IndexError: list index out of range

**Comment by eli64s** [comment]
@nachimehta Just pushed an update. Download the latest version using:

```sh
pip install --upgrade readmeai
```
Ley me know if you face anymore issues!

Thank you,
_Eli_
