### ISSUE TITLE
Error generating readme: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by ucukertz** [eli64s/readme-ai#94]
OS: Windows 10
I have tried running the shell as administrator and it still gives the exact same error. Is there anything else I could try?

```
PS D:\dev\ti\projects\PROJECTNAME> readmeai -r . --api GEMINI -o ai.md -m gemini-pro
► INFO | 2024-03-21 10:50:40 | readmeai.config.settings | Loaded configuration file: settings/blacklist.toml
► INFO | 2024-03-21 10:50:40 | readmeai.config.settings | Loaded configuration file: settings/commands.toml
► INFO | 2024-03-21 10:50:40 | readmeai.config.settings | Loaded configuration file: settings/languages.toml
► INFO | 2024-03-21 10:50:40 | readmeai.config.settings | Loaded configuration file: settings/markdown.toml
► INFO | 2024-03-21 10:50:40 | readmeai.config.settings | Loaded configuration file: settings/parsers.toml
► INFO | 2024-03-21 10:50:40 | readmeai.config.settings | Loaded configuration file: settings/prompts.toml
► INFO | 2024-03-21 10:50:40 | readmeai.core.utils | GEMINI settings FOUND in environment!
► INFO | 2024-03-21 10:50:40 | readmeai._agent | Repository validated: repository='.' full_name='' host_domain='local' host='local' name='.'
► INFO | 2024-03-21 10:50:40 | readmeai._agent | LLM API settings: api='GEMINI' base_url='https://api.openai.com/v1/chat/completions' context_window=3999 encoder='cl100k_base' model='gemini-pro' temperature=0.9 tokens=650 top_p=0.9
Traceback (most recent call last):
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\readmeai\_agent.py", line 77, in readme_agent
    asyncio.run(readme_generator(conf, output_file))
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\readmeai\_agent.py", line 86, in readme_generator
    await clone_repository(conf.config.git.repository, temp_dir)
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\readmeai\services\git.py", line 83, in clone_repository
    await remove_hidden_contents(temp_dir_path)
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\readmeai\services\git.py", line 100, in remove_hidden_contents
    shutil.rmtree(item)
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 808, in rmtree
    return _rmtree_unsafe(path, onexc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 631, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onexc)
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 631, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onexc)
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 636, in _rmtree_unsafe
    onexc(os.unlink, fullname, err)
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\shutil.py", line 634, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'D:\\Users\\USERNAME\\AppData\\Local\\Temp\\tmp760n5qjo\\.git\\objects\\pack\\pack-86f33272c58b623035530fab3cbf693de6534b94.idx'  

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Scripts\readmeai.exe\__main__.py", line 7, in <module>
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\readmeai\cli\main.py", line 51, in main
    readme_agent(
  File "D:\Users\USERNAME\AppData\Local\Programs\Python\Python312\Lib\site-packages\readmeai\_agent.py", line 80, in readme_agent
    raise ReadmeGeneratorError(exc, traceback.format_exc()) from exc
readmeai._exceptions.ReadmeGeneratorError: ("Error generating readme: [WinError 5] Access is denied: 'D:\\\\Users\\\\USERNAME\\\\AppData\\\\Local\\\\Temp\\\\tmp760n5qjo\\\\.git\\\\objects\\\\pack\\\\pack-86f33272c58b623035530fab3cbf693de6534b94.idx'", 'Traceback (most recent call last):\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\readmeai\\_agent.py", line 77, in readme_agent\n    asyncio.run(readme_generator(conf, output_file))\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\runners.py", line 194, in run\n    return runner.run(main)\n           ^^^^^^^^^^^^^^^^\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\runners.py", line 118, in run\n    return self._loop.run_until_complete(task)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\asyncio\\base_events.py", line 684, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\readmeai\\_agent.py", line 86, in readme_generator\n    await clone_repository(conf.config.git.repository, temp_dir)\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\readmeai\\services\\git.py", line 83, in clone_repository\n    await remove_hidden_contents(temp_dir_path)\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\readmeai\\services\\git.py", line 100, in remove_hidden_contents\n    shutil.rmtree(item)\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\shutil.py", line 808, in rmtree\n    return _rmtree_unsafe(path, onexc)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\shutil.py", line 631, in _rmtree_unsafe\n    _rmtree_unsafe(fullname, onexc)\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\shutil.py", line 631, in _rmtree_unsafe\n    _rmtree_unsafe(fullname, onexc)\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\shutil.py", line 636, in _rmtree_unsafe\n    onexc(os.unlink, fullname, err)\n  File "D:\\Users\\USERNAME\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\shutil.py", line 634, in _rmtree_unsafe\n    os.unlink(fullname)\nPermissionError: [WinError 5] Access is denied: \'D:\\\\Users\\\\USERNAME\\\\AppData\\\\Local\\\\Temp\\\\tmp760n5qjo\\\\.git\\\\objects\\\\pack\\\\pack-86f33272c58b623035530fab3cbf693de6534b94.idx\'\n')
```

**Comment by msrouchou** [comment]
I am also encountering the same issue on Win11.

**Comment by jSydorowicz21** [comment]
Also ran into this issue, the pr above by @Zxilly fixed this issue for me. Worth implementing.

**Comment by thomasBontempsTecrisViattech** [comment]
Hello, I also have this error. 

I try to add the @Zxilly update but it don't change my problem. Here the error : 

``
Traceback (most recent call last):
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\site-packages\readmeai\_agent.py", line 77, in readme_agent
    asyncio.run(readme_generator(conf, output_file))
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\site-packages\readmeai\_agent.py", line 86, in readme_generator
    await clone_repository(conf.config.git.repository, temp_dir)
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\site-packages\readmeai\services\git.py", line 83, in clone_repository
    await remove_hidden_contents(temp_dir_path)
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\site-packages\readmeai\services\git.py", line 100, in remove_hidden_contents
    shutil.rmtree(item)
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\shutil.py", line 759, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\shutil.py", line 624, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\shutil.py", line 624, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\shutil.py", line 629, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\T_B\miniconda3\envs\readmeai\lib\shutil.py", line 627, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Accès refusé: 'C:\\Users\\T_B\\AppData\\Local\\Temp\\tmprbf4i_hv\\.git\\objects\\pack\\pack-b9b2dfaea236e6782cbb3426a9baf9e07884fa75.idx
``

I got Windows 11 and I use python 3.9.18 

Is there something else to try ?

**Comment by Zxilly** [comment]
@thomasBontempsTecrisViattech It's obvious that you didn't apply the patch correctly.
![image](https://github.com/eli64s/readme-ai/assets/31370133/4e388a6a-59ac-4035-95f5-4c5ac4fda8a4)

**Comment by thomasBontempsTecrisViattech** [comment]
> @thomasBontempsTecrisViattech It's obvious that you didn't apply the patch correctly. ![image](https://private-user-images.githubusercontent.com/31370133/333588910-4e388a6a-59ac-4035-95f5-4c5ac4fda8a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTQ2MzksIm5iZiI6MTcxNjU1NDMzOSwicGF0aCI6Ii8zMTM3MDEzMy8zMzM1ODg5MTAtNGUzODhhNmEtNTlhYy00MDM1LTk1ZjUtNGM1YWM0ZmRhOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEyMzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NjM3OTI5OGQ3YzU1YzhjZjZkZGVmYzdiYzRlZDBmMjE2MzNlNjQ3M2E0Y2EzN2ZlYTQ2NDk3ZDE3NzZkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vehBptncAEj0-1IZrwz9RmWl5VqhS338eVGP0dwakXo) ![image](https://private-user-images.githubusercontent.com/31370133/333588980-a863e174-02a2-4ba2-94a5-3635d1f3c4c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1NTQ2MzksIm5iZiI6MTcxNjU1NDMzOSwicGF0aCI6Ii8zMTM3MDEzMy8zMzM1ODg5ODAtYTg2M2UxNzQtMDJhMi00YmEyLTk0YTUtMzYzNWQxZjNjNGM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDEyMzg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkNjlhMWFhMzYwZDJiMWU3OWVlZTJiMTYyNjAxM2U1OTU2NTI0YTBiY2UzNTAxZmQ1OWE3ODYwZTJlMjMzMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fzjuN7KjoXwrWmdXL1JhyM0NK5FtP7tyKTN2c7qxLZI)

En effet, j'ai pourtant changé le code et je run avec la commande : 
python main.py -o readmeai.md -r "myRepo"

Y a-t-il une étape à réaliser pour que le code soit pris en compte ?

**Comment by PatrickGBecker** [comment]
I also received the PermissionError: [WinError 5] Access is denied. Using Windows 11, Python 3.12.0, Pip 25.2 with Rust Compiler and OpenAI API Key.
